# Generated by Django 5.1.1 on 2024-09-16 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicearea',
            old_name='poly',
            new_name='coordinates',
        ),
        migrations.AlterField(
            model_name='provider',
            name='currency',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='provider',
            name='language',
            field=models.CharField(max_length=2),
        ),
    ]
